### ISSUE TITLE
absent fields in models/Transaction.go

### ISSUE THREAD

**Issue by xcat** [MinterTeam/minter-explorer-tools#1]
I take data  from  ​/api​/v1​/addresses​/{address}​/transactions
For example:

```
{"txn":123,"hash":"MtXXXXXXXXXXX","nonce":347,"block":123,
"timestamp":"2019-06-16T14:31:32Z","fee":"0.100000000000000000","type":4,"payload":"","from":"Mx123",
"data":{
	"coin_to_buy":"SCIENCE",
	"coin_to_sell":"BIP",
	"value_to_buy":"1000.000000000000000000",
	"value_to_sell":"46.014458502294519654",
	"maximum_value_to_sell":"1000000000000000.000000000000000000"}},
```

but in models hasnt all fields.

```
type BuyCoinTxData struct {
	CoinToBuy          string `json:"coin_to_buy"`
	ValueToBuy         string `json:"value_to_buy"`
	CoinToSell         string `json:"coin_to_sell"`
	MaximumValueToSell string `json:"maximum_value_to_sell"`
}

```

**Comment by xcat** [comment]
I change only Sell and Buy structs 
type SellCoinTxData struct {
	CoinToSell        string `json:"coin_to_sell"`
	ValueToSell       string `json:"value_to_sell"`
	ValueToBuy        string `json:"value_to_buy"`
	CoinToBuy         string `json:"coin_to_buy"`
	MinimumValueToBuy string `json:"minimum_value_to_buy"`
}

type SellAllCoinTxData struct {
	CoinToSell        string `json:"coin_to_sell"`
	ValueToSell       string `json:"value_to_sell"`
	ValueToBuy        string `json:"value_to_buy"`
	CoinToBuy         string `json:"coin_to_buy"`
	MinimumValueToBuy string `json:"minimum_value_to_buy"`
}

type BuyCoinTxData struct {
	CoinToBuy          string `json:"coin_to_buy"`
	ValueToBuy         string `json:"value_to_buy"`
	CoinToSell         string `json:"coin_to_sell"`
	ValueToSell        string `json:"value_to_sell"`
	MaximumValueToSell string `json:"maximum_value_to_sell"`
}

**Comment by grkamil** [comment]
@xcat These models for the minter extender (for DB). Resources you can find here: https://github.com/MinterTeam/minter-explorer-api

**Comment by xcat** [comment]
@GrKamil I so in https://github.com/MinterTeam/minter-explorer-api. 
I need models to unmarshal data from explorer-api.

**Comment by grkamil** [comment]
I understood, but models in this repo to unmarshal data from the database. Resources for explorer-api  placed in the explorer-api repository (link above).

For example: https://github.com/MinterTeam/minter-explorer-api/blob/master/transaction/data_resources/sell_all_coin.go
